# Generated by Django 3.2.9 on 2021-12-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20211208_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='Data Science', max_length=255),
        ),
    ]
